name: CI/CD workflow

on: workflow_dispatch

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sentiment-app-onnx
  S3_BUCKET: mlops-lab11-models-kaspersky

jobs:
  integration:
    name: checks_and_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --group integration

      - name: Run ruff checks
        run: pre-commit run

      - name: Run pytest
        run: uv run pytest tests -rP

  deployment:
    name: deploy_model_on_aws
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Configure AWS credenitials
        uses: aws-actions/configure-aws-credentials@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --group deployment

      - name: Run main.py to download artifacts from s3 and export them as ONNX model
        run: uv run main.py

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build and Push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sentiment-app-onnx
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REPOSITORY:$IMAGE_TAG .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG